variables:
    DOCKER_REGISTRY: "reg.nic.cz"
    # Set up pip cache shared between all jobs of the project.
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONWARNINGS: ""
    TOX_PARALLEL_NO_SPINNER: 1

stages:
    - test
    - build
    - publish

cache:
    paths:
        - .cache/pip

########################################################################################################################
# Basic declarations
.py37: &py37
    image: "$DOCKER_REGISTRY/python/tox:3.7"

.py38: &py38
    image: "$DOCKER_REGISTRY/python/tox:3.8"

.py39: &py39
    image: "$DOCKER_REGISTRY/python/tox:3.9"

.py310: &py310
    image: "$DOCKER_REGISTRY/python/tox:3.10"

.py311: &py311
    image: "$DOCKER_REGISTRY/python/tox:3.11"

.test: &test
    stage: test
    before_script:
        - echo "Active index - $PIP_INDEX_URL"
        # First, build all virtualenvs without actually executing any tests.
        - tox --parallel all --notest
    script:
        - tox
    coverage: '/TOTAL(?:\s+\d+){4}\s+(\d+\%)/'
    interruptible: true

########################################################################################################################
# Individual jobs
licensing:
    image: "$DOCKER_REGISTRY/utils/license-check:latest"
    tags:
        - common
    script:
        - license-check -v

test:py37:
    <<: *test
    <<: *py37

test:py38:
    <<: *test
    <<: *py38

test:py39:
    <<: *test
    <<: *py39

test:py310:
    <<: *test
    <<: *py310

test:py311:
    <<: *test
    <<: *py311

build:
    stage: build
    image: "$DOCKER_REGISTRY/python/upload:latest"
    script:
        - python3 -m build
    artifacts:
        paths:
            - dist
        expire_in: 1h
    needs: []

publish:
    stage: publish
    image: "$DOCKER_REGISTRY/python/upload:latest"
    script:
        - ls dist
        - devpi use "https://pypi.nic.cz/cznic/test"
        - devpi login ciuser --password "$DEVPI_PASSWORD"
        - devpi upload dist/*
    needs: ["build"]
    rules:
        - if: $CI_COMMIT_TAG
