variables:
    DOCKER_REGISTRY: "reg.nic.cz"
    # Set up pip cache shared between all jobs of the project.
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONWARNINGS: ""
    TOX_PARALLEL_NO_SPINNER: 1

cache:
    paths:
        - .cache/pip

########################################################################################################################
# Basic declarations
.py36: &py36
    image: "$DOCKER_REGISTRY/python/tox:3.6"

.py37: &py37
    image: "$DOCKER_REGISTRY/python/tox:3.7"

.py38: &py38
    image: "$DOCKER_REGISTRY/python/tox:3.8"

.py39: &py39
    image: "$DOCKER_REGISTRY/python/tox:3.9"

.test: &test
    before_script:
        - echo "Active index - $PIP_INDEX_URL"
        # First, build all virtualenvs without actually executing any tests.
        - tox --parallel all --notest
    script:
        - tox
    coverage: '/TOTAL(?:\s+\d+){4}\s+(\d+\%)/'
    interruptible: true

########################################################################################################################
# Individual jobs
licensing:
    image: "$DOCKER_REGISTRY/utils/license-check:latest"
    tags:
        - common
    script:
        - license-check -v

test:py36:
    <<: *test
    <<: *py36

test:py37:
    <<: *test
    <<: *py37

test:py38:
    <<: *test
    <<: *py38

test:py39:
    <<: *test
    <<: *py39
